### ISSUE TITLE
Twitter functionality can now be removed with latest Discord update

### ISSUE THREAD

**Issue by Syampuuh** [JeremyRuhland/saucebot-discord#11]
In the last two or three days Discord has improved their Twitter embedding to include all images in a Twitter post.

Desktop app:
![2019-11-20_19-26-56](https://user-images.githubusercontent.com/25516124/69292420-bfa8d180-0bcb-11ea-9632-2532b249fa15.png)

Mobile (Android):
![Screenshot_20191120-192746](https://user-images.githubusercontent.com/25516124/69292510-f979d800-0bcb-11ea-8d64-72fe966c7ba7.png)

**Comment by goopypanther** [comment]
Now implemented in ce704bf8f27a54d400a883af2ce437be852e68da and 44c760f59f6cece7651229c71ed5c560600b62c9
