### ISSUE TITLE
Reposting Twitter Links

### ISSUE THREAD

**Issue by JohnGlacious** [JeremyRuhland/saucebot-discord#27]
Seems like, as of recent, Twitter has fixed their embedding problem that was around for a little while. Now that the embed is back, sauce seems to not have been updated yet to not post Twitter links anymore.

Seems to have happened starting a week ago so I can understand it being unnoticed.

**Comment by goopypanther** [comment]
Yes, I think I'm seeing this as well. Tweets that discord use to ignore are now generating native embeds again. I should be able to turn the twitter feature off once I test a little bit more.

**Comment by goopypanther** [comment]
Twitter embedding has been disabled again
