### ISSUE TITLE
Saucebot spoils spoilers

### ISSUE THREAD

**Issue by dragon-architect** [JeremyRuhland/saucebot-discord#7]
![Screen Shot 2019-03-31 at 6 14 14 PM](https://user-images.githubusercontent.com/16181650/55296637-e7032200-53e1-11e9-8694-0677766dbd15.png)
A member of my own Discord server accidentally stumbled across this bug that seems to be a consequence of Discord's new "spoilers" feature!

EDIT: Apparently Github is broken in Firefox for me and failed to properly upload the screenshot. 😐

**Comment by goopypanther** [comment]
Fixed in commit https://github.com/JeremyRuhland/saucebot-discord/commit/e07174f4b74d95804a9ce2746a0011ccf9f0032b
