### ISSUE TITLE
Pixiv links stopped working

### ISSUE THREAD

**Issue by Demicol** [JeremyRuhland/saucebot-discord#8]
Pixiv changed how their URL's work and saucebot no longer picks up Pixiv links.

Before: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=70221117
Now: https://www.pixiv.net/en/artworks/70221117

**Comment by goopypanther** [comment]
Do you know if /en/ is determined by the country of the user or if its some kind of localization setting? Does it seem to always appear in the url to every art post page?

**Comment by Demicol** [comment]
I tested by changing my language in the pixiv profile settings, every other language beside English simply just has pixiv.net/artworks/ while English has pixiv.net/en/artworks/

**Comment by goopypanther** [comment]
Fix implemented in c7a348a57e1ced49abffcfad5cb9fe0c5e10c488
